export enum RoomResponses {
  ROOM_CREATED = "room_created",
  ROOM_CREATION_FAILED = "room_creation_failed",
  ROOM_JOINED = "room_joined",
  ROOM_JOINEDAS_SPECTATOR = "room_joined_as_spectator",
  ROLE_CHANGED = "role_changed",
  ROOM_SETTINGS_CHANGED = "room_settings_changed",
  SPECTATORS_OFF = "spectators_off",
  PLAYER_RECONNECTED = "player_reconnected",
  REMOVED_PLAYER = "removed_player",
  BANNED_PLAYER = "banned_player",
  BANNED_PLAYER_NOT_FOUND = "banned_player_not_found",
  PLAYER_UBANNED = "player_ubanned",
  ROOM_FOUND = "room_found",
  FULL_ROOM = "full_room",
  LEFT_ROOM = "left_room",
  ROOM_CLOSED = "room_closed",
  PUBLIC_ROOMS = "public_rooms",
  INVALID_SLOT = "invalid_slot",
  DATA_ERROR = "data_error",
}